Update Title on page change
AY2021S1-CS2103T-T11-4/tp pull request #78
Opened 2020-10-13 13:55 UTC by sogggy

2020-10-13 14:02 UTC, sogggy commented
Close #80

2020-10-13 14:05 UTC, wenhaogoh requested changes

2020-10-13 14:05 UTC, wenhaogoh commented on src/main/java/seedu/address/logic/LogicManager.java
> +    public boolean getIsExpenditure() {
Perhaps the naming should be "isExpenditure"?

2020-10-13 14:05 UTC, wenhaogoh commented on src/main/java/seedu/address/ui/MainWindow.java
> +                return logic.getPageTitle();
Is this condition redundant?

2020-10-14 05:42 UTC, wenhaogoh approved these changes
LGTM

2020-10-14 05:44 UTC, davidliew9 approved these changes
LGTM

2020-10-14 05:44 UTC, merged